import type { ImageSourcePropType } from 'react-native';

export const LETTER_IMAGES: Record<string, ImageSourcePropType> = {
  'a': require('../assets/asl/letters/a.png'),
  'b': require('../assets/asl/letters/b.png'),
  'c': require('../assets/asl/letters/c.png'),
  'd': require('../assets/asl/letters/d.png'),
  'e': require('../assets/asl/letters/e.png'),
  'f': require('../assets/asl/letters/f.png'),
  'g': require('../assets/asl/letters/g.png'),
  'h': require('../assets/asl/letters/h.png'),
  'i': require('../assets/asl/letters/i.png'),
  'j': require('../assets/asl/letters/j.png'),
  'k': require('../assets/asl/letters/k.png'),
  'l': require('../assets/asl/letters/l.png'),
  'm': require('../assets/asl/letters/m.png'),
  'n': require('../assets/asl/letters/n.png'),
  'o': require('../assets/asl/letters/o.png'),
  'p': require('../assets/asl/letters/p.png'),
  'q': require('../assets/asl/letters/q.png'),
  'r': require('../assets/asl/letters/r.png'),
  's': require('../assets/asl/letters/s.png'),
  't': require('../assets/asl/letters/t.png'),
  'u': require('../assets/asl/letters/u.png'),
  'v': require('../assets/asl/letters/v.png'),
  'w': require('../assets/asl/letters/w.png'),
  'x': require('../assets/asl/letters/x.png'),
  'y': require('../assets/asl/letters/y.png'),
  'z': require('../assets/asl/letters/z.png'),
};
