import type { ImageSourcePropType } from 'react-native';

/**
 * Drop-in PNG maps for vocab modules.
 * Generated by scripts/gen-asl-image-maps.js. Do not edit by hand.
 * Add `assets/asl/{module}/{signId}.png` then re-run the script.
 */
export const MODULE_IMAGES: Record<
  string,
  Record<string, ImageSourcePropType>
> = {
  'conversation': {
    'again': require('../assets/asl/conversation/again.png'),
    'excuse-me': require('../assets/asl/conversation/excuse-me.png'),
    'good-morning': require('../assets/asl/conversation/good-morning.png'),
    'goodbye': require('../assets/asl/conversation/goodbye.png'),
    'hello': require('../assets/asl/conversation/hello.png'),
    'im-fine': require('../assets/asl/conversation/im-fine.png'),
    'nice-to-meet-you': require('../assets/asl/conversation/nice-to-meet-you.png'),
    'no': require('../assets/asl/conversation/no.png'),
    'please': require('../assets/asl/conversation/please.png'),
    'thank-you': require('../assets/asl/conversation/thank-you.png'),
    'yes': require('../assets/asl/conversation/yes.png'),
    'youre-welcome': require('../assets/asl/conversation/youre-welcome.png'),
  },
  'wh-questions': {},
  'emotions': {
    'angry': require('../assets/asl/emotions/angry.png'),
    'happy': require('../assets/asl/emotions/happy.png'),
    'love': require('../assets/asl/emotions/love.png'),
    'sad': require('../assets/asl/emotions/sad.png'),
    'scared': require('../assets/asl/emotions/scared.png'),
  },
  'animals': {
    'bird': require('../assets/asl/animals/bird.png'),
    'cat': require('../assets/asl/animals/cat.png'),
    'dog': require('../assets/asl/animals/dog.png'),
    'fish': require('../assets/asl/animals/fish.png'),
  },
  'food': {
    'apple': require('../assets/asl/food/apple.png'),
    'bread': require('../assets/asl/food/bread.png'),
    'drink': require('../assets/asl/food/drink.png'),
    'eat': require('../assets/asl/food/eat.png'),
    'water': require('../assets/asl/food/water.png'),
  },
  'body-parts': {
    'arm': require('../assets/asl/body-parts/arm.png'),
    'ear': require('../assets/asl/body-parts/ear.png'),
    'eye': require('../assets/asl/body-parts/eye.png'),
    'hand': require('../assets/asl/body-parts/hand.png'),
    'head': require('../assets/asl/body-parts/head.png'),
  },
  'work': {
    'boss': require('../assets/asl/work/boss.png'),
    'job': require('../assets/asl/work/job.png'),
    'meeting': require('../assets/asl/work/meeting.png'),
    'office': require('../assets/asl/work/office.png'),
    'work': require('../assets/asl/work/work.png'),
  },
  'internet': {
    'download': require('../assets/asl/internet/download.png'),
    'internet': require('../assets/asl/internet/internet.png'),
    'message': require('../assets/asl/internet/message.png'),
    'sent': require('../assets/asl/internet/sent.png'),
    'video-call': require('../assets/asl/internet/video-call.png'),
    'wifi': require('../assets/asl/internet/wifi.png'),
  },
  'school': {
    'book': require('../assets/asl/school/book.png'),
    'homework': require('../assets/asl/school/homework.png'),
    'school': require('../assets/asl/school/school.png'),
    'student': require('../assets/asl/school/student.png'),
    'teacher': require('../assets/asl/school/teacher.png'),
  },
  'sports': {
    'ball': require('../assets/asl/sports/ball.png'),
    'play': require('../assets/asl/sports/play.png'),
    'run': require('../assets/asl/sports/run.png'),
    'sports': require('../assets/asl/sports/sports.png'),
    'swim': require('../assets/asl/sports/swim.png'),
  },
};
