import type { ImageSourcePropType } from 'react-native';

/**
 * Drop-in PNG maps for vocab modules.
 * Generated by scripts/gen-asl-image-maps.js. Do not edit by hand.
 * Add `assets/asl/{module}/{signId}.png` then re-run the script.
 */
export const MODULE_IMAGES: Record<
  string,
  Record<string, ImageSourcePropType>
> = {
  'conversation': {},
  'wh-questions': {},
  'emotions': {},
  'animals': {},
  'food': {},
  'body-parts': {},
  'work': {},
  'internet': {},
  'school': {},
  'sports': {},
};
